[project]
name = "sneaky-cat-2d-devtools"
version = "0.1.0"
requires-python = ">=3.10"

[dependency-groups]
dev = [
  "pre-commit>=3.7",
  "gdtoolkit==4.3.0",
]

[tool.gdlint]
disable = [
  "class-name",
]

[tool.gdformat]
line_length = 100
use_tabs = true
