name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  gut:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.5.1"
          use-dotnet: false
          include-templates: false

      - name: Show Godot version
        run: |
          which godot
          godot --version

      - name: Import project (headless)
        run: |
          godot --headless --quit --path .

      - name: Run GUT tests
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh -gdir=res://tests -gexit -ginclude_subdirs


